# coding: utf-8

"""
    OpenAPI

    tinkoff.ru/invest OpenAPI.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: al.a.volkov@tinkoff.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.market_order_response import MarketOrderResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestMarketOrderResponse(unittest.TestCase):
    """MarketOrderResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMarketOrderResponse(self):
        """Test MarketOrderResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.market_order_response.MarketOrderResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
