# coding: utf-8

"""
    OpenAPI

    tinkoff.ru/invest OpenAPI.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: al.a.volkov@tinkoff.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.search_market_instrument_response import SearchMarketInstrumentResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestSearchMarketInstrumentResponse(unittest.TestCase):
    """SearchMarketInstrumentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchMarketInstrumentResponse(self):
        """Test SearchMarketInstrumentResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.search_market_instrument_response.SearchMarketInstrumentResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
