# coding: utf-8

"""
    OpenAPI

    tinkoff.ru/invest OpenAPI.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: al.a.volkov@tinkoff.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.user_accounts import UserAccounts  # noqa: E501
from swagger_client.rest import ApiException


class TestUserAccounts(unittest.TestCase):
    """UserAccounts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserAccounts(self):
        """Test UserAccounts"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_accounts.UserAccounts()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
