# coding: utf-8

"""
    OpenAPI

    tinkoff.ru/invest OpenAPI.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: al.a.volkov@tinkoff.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.trade_status import TradeStatus  # noqa: E501
from swagger_client.rest import ApiException


class TestTradeStatus(unittest.TestCase):
    """TradeStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTradeStatus(self):
        """Test TradeStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.trade_status.TradeStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
