# coding: utf-8

"""
    OpenAPI

    tinkoff.ru/invest OpenAPI.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: al.a.volkov@tinkoff.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MarketOrderRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'lots': 'int',
        'operation': 'OperationType'
    }

    attribute_map = {
        'lots': 'lots',
        'operation': 'operation'
    }

    def __init__(self, lots=None, operation=None):  # noqa: E501
        """MarketOrderRequest - a model defined in Swagger"""  # noqa: E501
        self._lots = None
        self._operation = None
        self.discriminator = None
        self.lots = lots
        self.operation = operation

    @property
    def lots(self):
        """Gets the lots of this MarketOrderRequest.  # noqa: E501


        :return: The lots of this MarketOrderRequest.  # noqa: E501
        :rtype: int
        """
        return self._lots

    @lots.setter
    def lots(self, lots):
        """Sets the lots of this MarketOrderRequest.


        :param lots: The lots of this MarketOrderRequest.  # noqa: E501
        :type: int
        """
        if lots is None:
            raise ValueError("Invalid value for `lots`, must not be `None`")  # noqa: E501

        self._lots = lots

    @property
    def operation(self):
        """Gets the operation of this MarketOrderRequest.  # noqa: E501


        :return: The operation of this MarketOrderRequest.  # noqa: E501
        :rtype: OperationType
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """Sets the operation of this MarketOrderRequest.


        :param operation: The operation of this MarketOrderRequest.  # noqa: E501
        :type: OperationType
        """
        if operation is None:
            raise ValueError("Invalid value for `operation`, must not be `None`")  # noqa: E501

        self._operation = operation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MarketOrderRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MarketOrderRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
